#!/usr/bin/env bash

# Mendefinisikan path sumber (relatif terhadap posisi skrip)
SOURCE_DIR="src/config"
TARGET_DIR="$HOME/.config"

# Pastikan folder target (~/.config) sudah ada
mkdir -p "$TARGET_DIR"

echo "=============Run======================"
for dir in "$SOURCE_DIR"/*; do
    if [ -d "$dir" ]; then
        folder_name=$(basename "$dir")
        echo "📦 Deploying: $folder_name ke $TARGET_DIR/$folder_name"
        cp -rfu "$dir" "$TARGET_DIR/"
        sleep 0.2
    fi
done

echo "=========Done=====================" 
